# Site name
site_name: PLT Anomaly Detection Official Documentation

nav:
  - Home: index.md
  - Introduction: quickstart.md
  - Install Guide: install.md
  - API: API.md
  
theme:
    name: "readthedocs"

plugins:
    - search
    - mkdocstrings