# Site name
site_name: PLT Anomaly Detection Official Documentation

nav:
  - Home: index.md
  - Introduction: quickstart.md
  - Install: install.md
  - API: API.md
  
theme:
    feaures:
      - tabs
    name: material
    icon:
      logo: material/cloud
    font:
      text: Ubuntu
      code: Ubuntu Mono
    static_templates:
      - 404.html

plugins:
  - search
  - pdf-export:
      verbose: True
      media_type: print
      combined: True
      combined_output_path: pdf/combined.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: datetime
